env:
  browser: true
  es2021: true
  jest: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/react-in-jsx-scope: off
settings:
  react:
    version: detect
