env:
  browser: true
  es2021: true
  jest: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/react-in-jsx-scope: off
  quotes: ["error", "double"]
  no-trailing-spaces: "error"
  react/prop-types: "off"
  react/no-unescaped-entities: "off"
  curly: ["error", "all"] 
  eol-last: ["error", "always"]
  no-multiple-empty-lines: ["error", {"max": 1, "maxEOF": 1 }]
  max-lines: ["error", { "max": 300, "skipBlankLines": true, "skipComments": true }]
  prefer-const: ["error", { "destructuring": "any", "ignoreReadBeforeAssign": false }]
  max-depth: ["error", 4]
settings:
  react:
    version: detect



